"""test

Revision ID: 28feb1cc925b
Revises: 15cc48704512
Create Date: 2023-11-14 10:11:48.296769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28feb1cc925b'
down_revision: Union[str, None] = '15cc48704512'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owner_pets',
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], name=op.f('fk_owner_pets_owner_id_owners')),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name=op.f('fk_owner_pets_pet_id_pets')),
    sa.PrimaryKeyConstraint('owner_id', 'pet_id', name=op.f('pk_owner_pets'))
    )
    op.drop_table('pet_owners')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pet_owners',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('pet_id', sa.INTEGER(), nullable=True),
    sa.Column('owner_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], name='fk_pet_owners_owner_id_owners'),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name='fk_pet_owners_pet_id_pets'),
    sa.PrimaryKeyConstraint('id', name='pk_pet_owners')
    )
    op.drop_table('owner_pets')
    # ### end Alembic commands ###
